gripper:
  type: effort_controllers/JointTrajectoryController
  joints:
     - gripper_finger1_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0
      gripper_finger1_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    # gripper_finger1_joint: {p: 10, d: 0, i: 0, i_clamp: 0}
    gripper_finger1_joint: {p: 10000, d: 100, i: 5, i_clamp: 1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
